# CSV + API

In this reboot, we are going to use:

- The [Goodreads books](https://www.kaggle.com/jealousleopard/goodreadsbooks) dataset from Kaggle.
- The [Open Library Books API](https://openlibrary.org/dev/docs/api/books)

The goal of this livecode is to load the data from a CSV + loop over rows to enrich each row with information such as:

- List of subjects (Science, Humor, Travel, etc.)
- The cover URL of the book
- Other information you'd find useful in the JSON API

First, download the CSV in the local folder:

In [42]:
!curl -L https://wagon-public-datasets.s3.amazonaws.com/02-Data-Toolkit/02-Data-Sourcing/books.csv > books.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1509k  100 1509k    0     0   577k      0  0:00:02  0:00:02 --:--:--  577k

In [43]:
!ls -lh

total 4296
-rw-r--r--@ 1 scooter  staff   1.5M Oct  8 17:37 books.csv
-rw-r--r--@ 1 scooter  staff   579B Jan 18  2026 README.md
-rw-r--r--@ 1 scooter  staff    31K Oct  8 17:36 Recap.ipynb

Then import the usual suspects!

In [44]:
import requests
import pandas as pd
import numpy as np

## Load books from CSV

In [45]:
books_df = pd.read_csv('books.csv')
books_df.head(10)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling-Mary GrandPré,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling-Mary GrandPré,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling-Mary GrandPré,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling-Mary GrandPré,4.55,043965548X,9780439655484,eng,435,2149872,33964
5,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling-Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,38872,154
6,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.69,0976540606,9780976540601,en-US,152,18,1
7,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,27410,820
8,12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,0517226952,9780517226957,eng,815,3602,258
9,13,The Ultimate Hitchhiker's Guide to the Galaxy,Douglas Adams,4.38,0345453743,9780345453747,eng,815,240189,3954

In [22]:
# url = "https://openlibrary.org/api/books?bibkeys=ISBN:0439785960&format=json&jscmd=data"
# requests.get(url).json()

# Make a function that would take a single ISBN, and returns a url for the cover of the book
def cover_from_isbn(isbn):
    # construct the url
    url = f"https://openlibrary.org/api/books?bibkeys=ISBN:{isbn}&format=json&jscmd=data"
    # get the json from the API
    data = requests.get(url).json()
    # dig into the dict to get the cover url
    return data[f"ISBN:{isbn}"]['cover']['large']

In [46]:
# Iterate over the first 10 rows and call the function cover_from_isbn on each book
for index, book in books_df.head(10).iterrows():
    cover_url = cover_from_isbn(book["isbn"])
    # set the url as a new column in the dataframe `cover_url`
    books_df.loc[index, 'cover_url'] = cover_url

In [51]:
books_df.head(20)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count,cover_url
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling-Mary GrandPré,4.56,0439785960,9780439785969,eng,652,1944099,26249,https://covers.openlibrary.org/b/id/15156081-L...
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling-Mary GrandPré,4.49,0439358078,9780439358071,eng,870,1996446,27613,https://covers.openlibrary.org/b/id/12025650-L...
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling-Mary GrandPré,4.47,0439554934,9780439554930,eng,320,5629932,70390,https://covers.openlibrary.org/b/id/7572543-L.jpg
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272,https://covers.openlibrary.org/b/id/10301720-L...
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling-Mary GrandPré,4.55,043965548X,9780439655484,eng,435,2149872,33964,https://covers.openlibrary.org/b/id/8778528-L.jpg
5,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling-Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,38872,154,https://covers.openlibrary.org/b/id/278981-L.jpg
6,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.69,0976540606,9780976540601,en-US,152,18,1,https://covers.openlibrary.org/b/id/742235-L.jpg
7,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,27410,820,https://covers.openlibrary.org/b/id/279436-L.jpg
8,12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,0517226952,9780517226957,eng,815,3602,258,https://covers.openlibrary.org/b/id/12617870-L...
9,13,The Ultimate Hitchhiker's Guide to the Galaxy,Douglas Adams,4.38,0345453743,9780345453747,eng,815,240189,3954,https://covers.openlibrary.org/b/id/14656530-L...
10,14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4416,408,NaN
11,16,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams-Stephen Fry,4.22,0739322206,9780739322208,eng,6,1222,253,NaN
12,18,The Ultimate Hitchhiker's Guide (Hitchhiker's ...,Douglas Adams,4.38,0517149257,9780517149256,en-US,815,2801,192,NaN
13,21,A Short History of Nearly Everything,Bill Bryson-William Roberts,4.20,076790818X,9780767908184,eng,544,228522,8840,NaN
14,22,Bill Bryson's African Diary,Bill Bryson,3.43,0767915062,9780767915069,eng,55,6993,470,NaN
15,23,Bryson's Dictionary of Troublesome Words: A Wr...,Bill Bryson,3.88,0767910435,9780767910439,eng,256,2020,124,NaN
16,24,In a Sunburned Country,Bill Bryson,4.07,0767903862,9780767903868,eng,335,68213,4077,NaN
17,25,I'm a Stranger Here Myself: Notes on Returning...,Bill Bryson,3.90,076790382X,9780767903820,eng,304,47490,2153,NaN
18,26,The Lost Continent: Travels in Small Town America,Bill Bryson,3.83,0060920084,9780060920081,en-US,299,43779,2146,NaN
19,27,Neither Here nor There: Travels in Europe,Bill Bryson,3.87,0380713802,9780380713806,eng,254,46397,2127,NaN

Let's add a new column

In [ ]:
# YOUR CODE HERE

## API - Open Library

In [ ]:
# YOUR CODE HERE

## Calling the API with multiple ISBNs at a time

In [48]:
# Get all the cover URL for every single books in the df
# Think of how we can make the query parameters where 50 ISBNs are combined together
# Think of how we batch process the response back from the API

In [76]:
# Make a function that takes a list of ISBNs, and then returns (list / dict) of cover URLs
# https://openlibrary.org/api/books?bibkeys=ISBN:0385472579,ISBN:62019420&format=json

def covers_from_isbns(isbns):
  # build the query param for bibkeys
  bibkeys = f"ISBN:{",ISBN:".join(isbns)}"
  # build the url
  url = f"https://openlibrary.org/api/books?bibkeys={bibkeys}&format=json&jscmd=data"

  data = requests.get(url).json()

  # create a return list
  cover_urls = []
  # put all the cover url into the list
  for key in data.keys():
    cover_urls.append(data[key]['cover']['large'])
  # and return
  return cover_urls

In [85]:
isbns = list(books_df['isbn'])
isbns

['0439785960',
 '0439358078',
 '0439554934',
 '0439554896',
 '043965548X',
 '0439682584',
 '0976540606',
 '0439827604',
 '0517226952',
 '0345453743',
 '1400052920',
 '0739322206',
 '0517149257',
 '076790818X',
 '0767915062',
 '0767910435',
 '0767903862',
 '076790382X',
 '0060920084',
 '0380713802',
 '0380727501',
 '0380715430',
 '0345538374',
 '0618517650',
 '0618346244',
 '0618346252',
 '0618260587',
 '0618391002',
 '0618510826',
 '0618153977',
 '193337201X',
 '097669400X',
 '0689840926',
 '1557344493',
 '0385326505',
 '1575606240',
 '1595580271',
 '1595962808',
 '0670059676',
 '0141312629',
 '0595321801',
 '1590301943',
 '0449146979',
 '0061159174',
 '006076273X',
 '0060749911',
 '0273704745',
 '1932386106',
 '096513671X',
 '0374517193',
 '0374280398',
 '0374519749',
 '0374522596',
 '0374518734',
 '0374522871',
 '0374519323',
 '0374516006',
 '0374520658',
 '0822205106',
 '0679734996',
 '1596670231',
 '1581807740',
 '0800793617',
 '0871202867',
 '0753454947',
 '0871209993',
 '1852402873',
 '0761129588',
 '0972016414',
 '1581805632',
 '0441294677',
 '0441102670',
 '0441172695',
 '0765306476',
 '0399128980',
 '0765353709',
 '0441104029',
 '0441328008',
 '034541005X',
 '0385732546',
 '0785260056',
 '0471780936',
 '0325001537',
 '006076287X',
 '0470045299',
 '0072262788',
 '0764569244',
 '0471933821',
 '0764559915',
 '0764584383',
 '0596523696',
 '0806523492',
 '0806525363',
 '0596527314',
 '0143035002',
 '0451528611',
 '0140449175',
 '0822001837',
 '1593080271',
 '0486437965',
 '1593081774',
 '0778322270',
 '0521313252',
 '0140183957',
 '0679767479',
 '1568491980',
 '0743270797',
 '0932863051',
 '0742508803',
 '0205358624',
 '1557344035',
 '0380720442',
 '0821925326',
 '043927169X',
 '0606105263',
 '0751506435',
 '006078671X',
 '0743499344',
 '0765313405',
 '1400032490',
 '1400032482',
 '1400032466',
 '0312424442',
 '0806930772',
 '0140366601',
 '0811201120',
 '080213016X',
 '0802131786',
 '0802151825',
 '0802151787',
 '0802151809',
 '0811201066',
 '0141439637',
 '1593080964',
 '0375700528',
 '1565842219',
 '0394743040',
 '080215154X',
 '2070388093',
 '1851681825',
 '156656249X',
 '014019553X',
 '0394431243',
 '0806501901',
 '067943920X',
 '0753453800',
 '1402714572',
 '1416500294',
 '0689854684',
 '0517221144',
 '1577658051',
 '037576013X',
 '0933121180',
 '0060531045',
 '0785950109',
 '8423919005',
 '0394800842',
 '0821778250',
 '0060733039',
 '8432216062',
 '0553348981',
 '0140120831',
 '1582881847',
 '0345413997',
 '0312863551',
 '0441788386',
 '074348844X',
 '0441748600',
 '0345316509',
 '0765314932',
 '0671742515',
 '0345455290',
 '0345418778',
 '0345476514',
 '0345368436',
 '1417622857',
 '0394820371',
 '0573650969',
 '0691122946',
 '0393329402',
 '0671867423',
 '0395883970',
 '0684848155',
 '0140156046',
 '0140152741',
 '0140119485',
 '0679722947',
 '0743244257',
 '0140179178',
 '0679722955',
 '159420120X',
 '0060930217',
 '0060931671',
 '0140283382',
 '0312423209',
 '0141180633',
 '0143039946',
 '0316724432',
 '0140189300',
 '140004314X',
 '0374522219',
 '0679754865',
 '0679752862',
 '0679754857',
 '0307264874',
 '0374529949',
 '0143039830',
 '0140097317',
 '014009735X',
 '0940650762',
 '0963188925',
 '0312426232',
 '0140115854',
 '0312263996',
 '038077108X',
 '0140154078',
 '0805081453',
 '0140178139',
 '0811214982',
 '2742741461',
 '1886224145',
 '0143036556',
 '0446579785',
 '052138673X',
 '0743203046',
 '034543871X',
 '0393318281',
 '1599869942',
 '0806519606',
 '0822549204',
 '0932813860',
 '0521437733',
 '0373792689',
 '0974514055',
 '0764585975',
 '0307281701',
 '0399529209',
 '0812969707',
 '0060255080',
 '0330485385',
 '159413023X',
 '0345360354',
 '0321303474',
 '0321430840',
 '3822840858',
 '0743264460',
 '0743236017',
 '0965762645',
 '0553572490',
 '0060589469',
 '0802789471',
 '0688060692',
 '185960515X',
 '1592530877',
 '0451528808',
 '0192833987',
 '0486451380',
 '0340837489',
 '0452011876',
 '0451163087',
 '0452286751',
 '0451163931',
 '0452281253',
 '0451187849',
 '0451147952',
 '0452274044',
 '0471791431',
 '0553803816',
 '0375755195',
 '1592283195',
 '0975599518',
 '0374502005',
 '0307263940',
 '0312405545',
 '019517013X',
 '1400079497',
 '0713998946',
 '0688171621',
 '0060932686',
 '1400034957',
 '0307350428',
 '0307350444',
 '140003454X',
 '1400095808',
 '0375708111',
 '086171492X',
 '184353584X',
 '1740598318',
 '1740594770',
 '186450353X',
 '8408064762',
 '1740592050',
 '0618710531',
 '0060512806',
 '2228894699',
 '2228894168',
 '0060733357',
 '0060593083',
 '0553383442',
 '0553573861',
 '0380816032',
 '0553380966',
 '0553383434',
 '0060833181',
 '0553380958',
 '344245302X',
 '1880685353',
 '1880685337',
 '0465067107',
 '0465051367',
 '0465067093',
 '0898709199',
 '0060887966',
 '0061122416',
 '142150460X',
 '1591169259',
 '1421504596',
 '1591169208',
 '1591169291',
 '006019250X',
 '1591169232',
 '0747588945',
 '0812974611',
 '158715739X',
 '0142000671',
 '0582461464',
 '0060554738',
 '014240120X',
 '0808553038',
 '1400096898',
 '0739326228',
 '0099498189',
 '1557046832',
 '0099771519',
 '074343059X',
 '0007229577',
 '1932664394',
 '0521750849',
 '0373510055',
 '0802415318',
 '1416524797',
 '849561877X',
 '0972859896',
 '0307277674',
 '076792603X',
 '2266144340',
 '1416524800',
 '0671027387',
 '0552151769',
 '0593055071',
 '9953299072',
 '1416524886',
 '078601606X',
 '0743409159',
 '0671015206',
 '1585424331',
 '1932429239',
 '0977616657',
 '1563410907',
 '0345479173',
 '0451205367',
 '1419349996',
 '1400098033',
 '0743226720',
 '0140481397',
 '0226014908',
 '1565122429',
 '1416500189',
 '0671823493',
 '0310258979',
 '0310264138',
 '0060838582',
 '0141006870',
 '0812968069',
 '0385340540',
 '0394720245',
 '0345480600',
 '0060193395',
 '1579546013',
 '0972018417',
 '0471743674',
 '0471430455',
 '0805431578',
 '0679838864',
 '0373250711',
 '0140143459',
 '0802732291',
 '030723827X',
 '1400052580',
 '0307346587',
 '1400052386',
 '0609609971',
 '1400052378',
 '0061234001',
 '8466625127',
 '0061245135',
 '9722334964',
 '0739455354',
 '0399153594',
 '0156030209',
 '8423335127',
 '0828808392',
 '0143034901',
 '0140285970',
 '0316646660',
 '0307276902',
 '1411677315',
 '0061171468',
 '0787968331',
 '0446394599',
 '0131494848',
 '1401359299',
 '0316861014',
 '0060574216',
 '0060192771',
 '0007152590',
 '0722538448',
 '006123205X',
 '0735200300',
 '0553381679',
 '0517542021',
 '0736606378',
 '5557075313',
 '0393324818',
 '0744005612',
 '0140280197',
 '055338368X',
 '0553812165',
 '0553295411',
 '0812590104',
 '038551641X',
 '0553381393',
 '0553382047',
 '0446691437',
 '0826413013',
 '0811701646',
 '0140442758',
 '0192802771',
 '0140449744',
 '0674990404',
 '0674994809',
 '0198145411',
 '0879756322',
 '189031823X',
 '0872207889',
 '0801435307',
 '0872204626',
 '0140449043',
 '0674991842',
 '0140449086',
 '0140446389',
 '0879757779',
 '0192824252',
 '0140440348',
 '0393959465',
 '0375400613',
 '0226327701',
 '0140275363',
 '0872203522',
 '0374529051',
 '0147712556',
 '0140447946',
 '0451527372',
 '0872205428',
 '0143039954',
 '0374525749',
 '0060931957',
 '0140449116',
 '0451527364',
 '086516584X',
 '067499583X',
 '1891190237',
 '0192837680',
 '155832125X',
 '0395754909',
 '0141000589',
 '0517092948',
 '0521618746',
 '0199267170',
 '1557831572',
 '006251279X',
 '0062513346',
 '0060527986',
 '0060832819',
 '0061122092',
 '0060930136',
 '0060589280',
 '0061124265',
 '0140714545',
 '0764586033',
 '0764585681',
 '0879232153',
 '0674991206',
 '0872201686',
 '0674991222',
 '0872203948',
 '0393971678',
 '0674991877',
 '0929524357',
 '0226307808',
 '0226307840',
 '0226307832',
 '1590171802',
 '0553213636',
 '0226307824',
 '0226307816',
 '0140449299',
 '0674995600',
 '0521643864',
 '0140447261',
 '0195125983',
 '0413752801',
 '0486424626',
 '0393325830',
 '0192832603',
 '0195061667',
 '067499566X',
 '090651598X',
 '0195145666',
 '071563187X',
 '0822004240',
 '0674995740',
 '0715629948',
 '0226307662',
 '0226307786',
 '0226307948',
 '019513592X',
 '0140443339',
 '0872203905',
 '0140441123',
 '0374527059',
 '081221627X',
 '0226307646',
 '0521539811',
 '1400041929',
 '0812216717',
 '0486292428',
 '1419150014',
 '0226307867',
 '0452011671',
 '0451527844',
 '015602764X',
 '0140444254',
 '0674995570',
 '0872205851',
 '0679431322',
 '0140440283',
 '0192835882',
 '1580495931',
 '0451621603',
 '0521617359',
 '1416500332',
 '0452007178',
 '0415907446',
 '0553213431',
 '0812234561',
 '0872203611',
 '0140448144',
 '1585100870',
 '0199120099',
 '0674995376',
 '0140449515',
 '0140441522',
 '0156027658',
 '0674995961',
 '0822007762',
 '0198721595',
 '0451616227',
 '0198140819',
 '0872206033',
 '0140443320',
 '0521774330',
 '0374500010',
 '1400032717',
 '0316156507',
 '0743477545',
 '0865471185',
 '0743482778',
 '0743271327',
 '0007205589',
 '0142000280',
 '0609610570',
 '843392463X',
 '8433968777',
 '1862076650',
 '8433924710',
 '8433924621',
 '0321317106',
 '0321365208',
 '8432216429',
 '9500716054',
 '1565480848',
 '0679783199',
 '1565481240',
 '0520227573',
 '0895269414',
 '0024021504',
 '0872201864',
 '0143035983',
 '0192854526',
 '1565482018',
 '0060934913',
 '8466308954',
 '0156001268',
 '014044789X',
 '0571191037',
 '0393058107',
 '0806128941',
 '0806114568',
 '0814317324',
 '0674992555',
 '0520242602',
 '0674990471',
 '0674990463',
 '0814326110',
 '0806115602',
 '069101597X',
 '0195143108',
 '0195143736',
 '0130158852',
 '0446594342',
 '1857150600',
 '0226301192',
 '0521315794',
 '0521011760',
 '0521479347',
 '1585424838',
 '0767907434',
 '0007149611',
 '0743233212',
 '0743270606',
 '0393061310',
 '848306667X',
 '0739467352',
 '0865475091',
 '0385486804',
 '0785268839',
 '0743246985',
 '044657967X',
 '0515142395',
 '0439227143',
 '037582538X',
 '1591583667',
 '0805063897',
 '0679724699',
 '0394417755',
 '0394751221',
 '0140268685',
 '0140137343',
 '0141439513',
 '014025157X',
 '0192802380',
 '0143036238',
 '0486440915',
 '1593083246',
 '1400032806',
 '0375752676',
 '0385494785',
 '0965778401',
 '067978361X',
 '0374292795',
 '8427032226',
 '0898868092',
 '0590422677',
 '0451529308',
 '1402714580',
 '0439101360',
 '0517221160',
 '1931082731',
 '1904633277',
 '0486406512',
 '0141439602',
 '0764586068',
 '0743487605',
 '1593081383',
 '158663352X',
 '1593080557',
 '1857151437',
 '079450390X',
 '067179227X',
 '0786903821',
 '1405228180',
 '0517093391',
 '0375760059',
 '0451530047',
 '0671882368',
 '0670030775',
 '0140436146',
 '0465031269',
 '0060183071',
 '8483066483',
 '0822533898',
 '0439314550',
 '043932162X',
 '0826452329',
 '0747584664',
 '0765342510',
 '0765342537',
 '0765342529',
 '0060833173',
 '0413772780',
 '1420926713',
 '0198144962',
 '0521834341',
 '1573921335',
 '0198145047',
 '1853991147',
 '1883011086',
 '1883011078',
 '0375415025',
 '0394758269',
 '0394758277',
 '0394757653',
 '0394758285',
 '0394757688',
 '0812970403',
 '1421501562',
 '056352474X',
 '067003472X',
 '068482471X',
 '0316180661',
 '0142003840',
 '0465073514',
 '0387987207',
 '0262540428',
 '0553345842',
 '0553103741',
 '0553804367',
 '055380202X',
 '0762419229',
 '0465081983',
 '039332446X',
 '0380707632',
 '0691050848',
 '0060977108',
 '0316281336',
 '0452282314',
 '0452278872',
 '0451191153',
 '0446618764',
 '0060793198',
 '1400051576',
 '1841150355',
 '0312425023',
 '0312424086',
 '0316172324',
 '0849945119',
 '073945529X',
 '0743422074',
 '0517147688',
 '0452286530',
 '0517118297',
 '0192832972',
 '0192802631',
 '097212179X',
 '0684830493',
 '0743564367',
 '0764586602',
 '0684718057',
 '0684163268',
 '0192840398',
 '0679731369',
 '0140435824',
 '0192836226',
 '0451528204',
 '0140448004',
 '0140447970',
 '0226735192',
 '0312422156',
 '0743270754',
 '1419364621',
 '0743223136',
 '1574671324',
 '0142437115',
 '0142437786',
 '076455302X',
 '0471773867',
 '0452281326',
 '0684842238',
 '0684839377',
 '0072920963',
 '0938497197',
 '0671708635',
 '0743250974',
 '0671887173',
 '1932073205',
 '0915811235',
 '0425179613',
 '0306814552',
 '0671869205',
 '140009691X',
 '067960085X',
 '0345478207',
 '0449007383',
 '0679745645',
 '073933364X',
 '0684868768',
 '0446671827',
 '0553245015',
 '0813527406',
 '0684842572',
 '0940450313',
 '1883011949',
 '0940450534',
 '0486420493',
 '0689304579',
 '0440802504',
 '0307236013',
 '1597770078',
 '0618056998',
 '0618083553',
 '0395291305',
 '0618574999',
 '0618009361',
 '0670910619',
 '067002922X',
 '0140271570',
 '0815319665',
 '0671792768',
 '0671447548',
 '0684813637',
 '0844662925',
 '0743262131',
 '0451188454',
 '0340682116',
 '8466305130',
 '9626343583',
 '0763630187',
 '0143058096',
 '1593080182',
 '0415247713',
 '0192781537',
 '0701124229',
 '0919123708',
 '019274156X',
 '0671463713',
 '0252063023',
 '0700607420',
 '0006531202',
 '0515139734',
 '0515121495',
 '0061020613',
 '0812967054',
 '1854583522',
 '0862921473',
 '0674996232',
 '0393977617',
 '0060654856',
 '0451528557',
 '0141439971',
 '0743487737',
 '0975579908',
 '157174102X',
 '0439436540',
 '1842124021',
 '0812970756',
 '0141441119',
 '0307264890',
 '0824512596',
 '1400083117',
 '0156007754',
 '0156001411',
 '0156010593',
 '0156013037',
 '0156005204',
 '0156028794',
 '0156004011',
 '1860465021',
 '8466312803',
 '8466314741',
 '846630679X',
 '0156006243',
 '9587043642',
 '089009389X',
 '000100039X',
 '0394448049',
 '0143036386',
 '0141182679',
 '0375711163',
 '382960226X',
 '0679725407',
 '0233989781',
 '0199110832',
 '0143034545',
 '0807744689',
 '0195137892',
 '0071460829',
 '0316346624',
 '0786887176',
 '0060521996',
 '0141439564',
 '0192833596',
 '0393960692',
 '0664241581',
 '0060935464',
 '0060888695',
 '044508376X',
 '0061205699',
 '0553381342',
 '0761501665',
 '0773762167',
 '0486287599',
 '1416500391',
 '1556434952',
 '0940450771',
 '0192834428',
 '1931082308',
 '193108288X',
 '1883011094',
 '1590171624',
 '0140424385',
 '019283360X',
 '014042234X',
 '0812000390',
 '0198711557',
 '0140444084',
 '0671475029',
 '0395290317',
 '0140150811',
 '0142001619',
 '0689834195',
 '0618446885',
 '039475526X',
 '0553580078',
 '0805202412',
 '0300115865',
 '1568813074',
 '074754655X',
 '1558745157',
 '0060515198',
 '0805061835',
 '0060987049',
 '0007179812',
 '0006548598',
 '0262632551',
 '0415283043',
 '0684832402',
 '0060838655',
 '1565848268',
 '1565847253',
 '0500203474',
 '0822318644',
 '0140135154',
 '039574010X',
 '006091307X',
 '0425181642',
 '0307237206',
 '094089548X',
 '0440936853',
 '0739439707',
 '0877887268',
 '0877880204',
 '0062545035',
 '0521639875',
 '0385092105',
 '1419154079',
 '0140433392',
 '0283352558',
 '0195114159',
 '140015068X',
 '0060734019',
 '0439366771',
 '0440841216',
 '0439271711',
 '0380652196',
 '0618654798',
 '0066239427',
 '0525464824',
 '1559704640',
 '078690206X',
 '0452284937',
 '0452287022',
 '0006513204',
 '0385415605',
 '052594978X',
 '0452283205',
 '0452284449',
 '0965903532',
 '3471772537',
 '1857093313',
 '1421506130',
 '1591164419',
 '1421506122',
 '1421502712',
 '1421504030',
 '4088736214',
 '4088736710',
 '4088736524',
 '0263755819',
 '0373028601',
 '0307277763',
 '3257228007',
 '0747534934',
 '0140105832',
 '0747566755',
 '4088732138',
 '2723442276',
 '3452200131',
 '0440410258',
 '0440229359',
 ...]

In [ ]:
final_list_of_urls = []

for small_isbns in np.array_split(isbns, 260):
    urls = covers_from_isbns(small_isbns)
    final_list_of_urls.append(urls)
    print(final_list_of_urls)

final_list_of_urls
# urls = covers_from_isbns(isbns)

KeyError: 'cover'

0     https://covers.openlibrary.org/b/id/15156081-L...
1     https://covers.openlibrary.org/b/id/12025650-L...
2     https://covers.openlibrary.org/b/id/7572543-L.jpg
3     https://covers.openlibrary.org/b/id/10301720-L...
4     https://covers.openlibrary.org/b/id/8778528-L.jpg
5      https://covers.openlibrary.org/b/id/278981-L.jpg
6      https://covers.openlibrary.org/b/id/742235-L.jpg
7      https://covers.openlibrary.org/b/id/279436-L.jpg
8     https://covers.openlibrary.org/b/id/12617870-L...
9     https://covers.openlibrary.org/b/id/14656530-L...
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
14                                                  NaN
15                                                  NaN
16                                                  NaN
17                                                  NaN
18                                                  NaN
19                                                  NaN
Name: cover_url, dtype: object