# Data sourcing

In [2]:
%%bash
mkdir -p data
curl -s https://wagon-public-datasets.s3.amazonaws.com/02-Data-Toolkit/02-Data-Sourcing/co2_sample.csv > data/co2_sample.csv
head -n 5 data/co2_sample.csv

country,2014,2015,2016,2017,2018,2019,2020,2021,2022
Afghanistan,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
Angola,1.64,1.22,1.18,1.15,1.12,1.15,1.12,1.2,1.23
Albania,2.25,2.04,2.01,2.13,2.08,2.05,2.0,2.12,2.1
Andorra,5.83,5.97,6.07,6.27,6.12,6.06,5.63,5.97,5.91

# Reading CSV with pandas

In [3]:
import pandas as pd

emission_df = pd.read_csv('./data/co2_pcap_cons.csv')
emission_df

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.28,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
1,Angola,0.009,0.009,0.009,0.009,0.009,0.009,0.010,0.010,0.010,...,1.28,1.640,1.220,1.180,1.150,1.120,1.150,1.120,1.200,1.230
2,Albania,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,2.27,2.250,2.040,2.010,2.130,2.080,2.050,2.000,2.120,2.100
3,Andorra,0.333,0.335,0.337,0.340,0.342,0.345,0.347,0.350,0.352,...,5.9,5.830,5.970,6.070,6.270,6.120,6.060,5.630,5.970,5.910
4,UAE,0.063,0.063,0.064,0.064,0.064,0.064,0.065,0.065,0.065,...,27,26.800,27.000,26.700,23.900,23.500,21.200,19.700,20.700,21.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Samoa,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,1.04,1.090,1.210,1.260,1.290,1.320,1.370,1.310,1.400,1.430
190,Yemen,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,0.994,0.937,0.480,0.377,0.363,0.356,0.365,0.362,0.387,0.395
191,South Africa,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,6.2,6.100,5.760,5.680,5.550,5.420,5.680,5.110,5.080,5.180
192,Zambia,0.255,0.256,0.257,0.258,0.259,0.260,0.261,0.262,0.263,...,0.511,0.560,0.519,0.471,0.474,0.467,0.487,0.388,0.416,0.424
193,Zimbabwe,0.059,0.060,0.060,0.060,0.060,0.061,0.061,0.061,0.061,...,0.906,0.929,0.955,0.821,0.708,0.830,0.783,0.737,0.789,0.804

# Getting bit more info

In [4]:
!curl -s https://wagon-public-datasets.s3.amazonaws.com/02-Data-Toolkit/02-Data-Sourcing/iso2_with_region.csv > data/iso2_with_region.csv
iso_df = pd.read_csv('data/iso2_with_region.csv', na_filter=False)
iso_df.head()

             Name Code       Full Name   Region
0     Afghanistan   AF     Afghanistan     Asia
1   Åland Islands   AX   Åland Islands   Europe
2         Albania   AL         Albania   Europe
3         Algeria   DZ         Algeria   Africa
4  American Samoa   AS  American Samoa  Oceania

In [5]:
emission_df

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.28,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
1,Angola,0.009,0.009,0.009,0.009,0.009,0.009,0.010,0.010,0.010,...,1.28,1.640,1.220,1.180,1.150,1.120,1.150,1.120,1.200,1.230
2,Albania,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,2.27,2.250,2.040,2.010,2.130,2.080,2.050,2.000,2.120,2.100
3,Andorra,0.333,0.335,0.337,0.340,0.342,0.345,0.347,0.350,0.352,...,5.9,5.830,5.970,6.070,6.270,6.120,6.060,5.630,5.970,5.910
4,UAE,0.063,0.063,0.064,0.064,0.064,0.064,0.065,0.065,0.065,...,27,26.800,27.000,26.700,23.900,23.500,21.200,19.700,20.700,21.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Samoa,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,1.04,1.090,1.210,1.260,1.290,1.320,1.370,1.310,1.400,1.430
190,Yemen,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,0.994,0.937,0.480,0.377,0.363,0.356,0.365,0.362,0.387,0.395
191,South Africa,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,6.2,6.100,5.760,5.680,5.550,5.420,5.680,5.110,5.080,5.180
192,Zambia,0.255,0.256,0.257,0.258,0.259,0.260,0.261,0.262,0.263,...,0.511,0.560,0.519,0.471,0.474,0.467,0.487,0.388,0.416,0.424
193,Zimbabwe,0.059,0.060,0.060,0.060,0.060,0.061,0.061,0.061,0.061,...,0.906,0.929,0.955,0.821,0.708,0.830,0.783,0.737,0.789,0.804

In [6]:
merged_df = emission_df.merge(iso_df, left_on='country', right_on='Name')
merged_df = merged_df.drop(columns=["country"])
merged_df

,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,...,2017,2018,2019,2020,2021,2022,Name,Code,Full Name,Region
0,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.247,0.254,0.261,0.261,0.279,0.284,Afghanistan,AF,Afghanistan,Asia
1,0.009,0.009,0.009,0.009,0.009,0.009,0.010,0.010,0.010,0.010,...,1.150,1.120,1.150,1.120,1.200,1.230,Angola,AO,Angola,Africa
2,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,2.130,2.080,2.050,2.000,2.120,2.100,Albania,AL,Albania,Europe
3,0.333,0.335,0.337,0.340,0.342,0.345,0.347,0.350,0.352,0.355,...,6.270,6.120,6.060,5.630,5.970,5.910,Andorra,AD,Andorra,Europe
4,0.063,0.063,0.064,0.064,0.064,0.064,0.065,0.065,0.065,0.065,...,23.900,23.500,21.200,19.700,20.700,21.100,UAE,AE,UAE,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,1.290,1.320,1.370,1.310,1.400,1.430,Samoa,WS,Samoa,Oceania
190,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,0.363,0.356,0.365,0.362,0.387,0.395,Yemen,YE,Yemen,Asia
191,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,5.550,5.420,5.680,5.110,5.080,5.180,South Africa,ZA,South Africa,Africa
192,0.255,0.256,0.257,0.258,0.259,0.260,0.261,0.262,0.263,0.264,...,0.474,0.467,0.487,0.388,0.416,0.424,Zambia,ZM,Zambia,Africa
193,0.059,0.060,0.060,0.060,0.060,0.061,0.061,0.061,0.061,0.062,...,0.708,0.830,0.783,0.737,0.789,0.804,Zimbabwe,ZW,Zimbabwe,Africa

## APIs

Making requests to the internet but in a machine readable way

In [7]:
import requests
from IPython.display import Image

url = "https://api.github.com/users/trouni"

response = requests.get(url).json()
Image(url = response['avatar_url'])

In [8]:
country_code = 'AE'
year = 2012

url = f"https://api.worldbank.org/v2/country/{country_code}/indicator/SP.POP.TOTL?date={year}&format=json"
response = requests.get(url).json()
response[1][0]['value']

7391448

In [9]:
def fetch_population_of_a_country(country, year):
    url = f"https://api.worldbank.org/v2/country/{country}/indicator/SP.POP.TOTL?date={year}&format=json"
    response = requests.get(url)
    data = response.json()

    if response.ok != True or data[1] == None:
        print('Failed')
        return None

    return data[1][0]["value"]

In [10]:
fetch_population_of_a_country('JP', 2023)

124516650

In [43]:
# iterate over each row of the df
# on each row, use the country code to get the population
# add that info as a new column

for index, row in merged_df.head(3).iterrows():
    population = fetch_population_of_a_country(row["Code"], 2012)
    merged_df.loc[index, 'Population'] = population

In [45]:
# Create empty lists as placeholders for the codes, names and populations
country_codes = []
country_names = []
populations = []

# Start at page 1 and start a while loop (we don't know how many pages we'll get)
page = 1
while True:
    url = f"https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL"

    params = {
        "format": "json",
        "date": year,
        "page": page,  # This is new: we pass the page we want as a param
    }

    response = requests.get(url=url, params=params).json()

    # Add the codes, names and populations to our placeholders
    country_codes.extend([result["country"]["id"] for result in response[1]])
    country_names.extend([result["country"]["value"] for result in response[1]])
    populations.extend(result["value"] for result in response[1])

    # Check if this wasn't the last page
    if page == response[0]["pages"]:
        break
    # Get ready for the next page
    page += 1

In [51]:
population_df = pd.DataFrame(
    {"Code": country_codes, "Name": country_names, "Population": populations}
)
population_df.merge(merged_df, left_on='Code', right_on='Code')

,Code,Name_x,Population_x,Name_y,Full Name,Region,Population_y,1800,1801,1802,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,AF,Afghanistan,30560034.0,Afghanistan,Afghanistan,Asia,30560034.0,0.001,0.001,0.001,...,0.28,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
1,AL,Albania,2860708.0,Albania,Albania,Europe,2860708.0,0.001,0.001,0.001,...,2.27,2.250,2.040,2.010,2.130,2.080,2.050,2.000,2.120,2.100
2,DZ,Algeria,37646166.0,Algeria,Algeria,Africa,NaN,0.000,0.000,0.000,...,3.48,3.680,3.800,3.640,3.560,3.690,3.770,3.690,3.800,3.880
3,AD,Andorra,76834.0,Andorra,Andorra,Europe,NaN,0.333,0.335,0.337,...,5.9,5.830,5.970,6.070,6.270,6.120,6.060,5.630,5.970,5.910
4,AO,Angola,25177394.0,Angola,Angola,Africa,25177394.0,0.009,0.009,0.009,...,1.28,1.640,1.220,1.180,1.150,1.120,1.150,1.120,1.200,1.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,VN,Viet Nam,89510356.0,Vietnam,Vietnam,Asia,NaN,0.015,0.015,0.015,...,1.19,1.390,1.610,1.640,1.590,1.810,2.190,2.100,2.130,2.170
189,PS,West Bank and Gaza,3979998.0,Palestine,Palestine,Asia,NaN,0.010,0.010,0.010,...,0.563,0.641,0.664,0.698,0.671,0.661,0.677,0.671,0.718,0.733
190,YE,"Yemen, Rep.",28433647.0,Yemen,Yemen,Asia,NaN,0.002,0.002,0.002,...,0.994,0.937,0.480,0.377,0.363,0.356,0.365,0.362,0.387,0.395
191,ZM,Zambia,14913629.0,Zambia,Zambia,Africa,NaN,0.255,0.256,0.257,...,0.511,0.560,0.519,0.471,0.474,0.467,0.487,0.388,0.416,0.424
192,ZW,Zimbabwe,13817887.0,Zimbabwe,Zimbabwe,Africa,NaN,0.059,0.060,0.060,...,0.906,0.929,0.955,0.821,0.708,0.830,0.783,0.737,0.789,0.804

In [26]:
new_order = ["Name",	"Code",	"Full Name",	"Region",	"Population"]

new_order += list(merged_df.columns[:-5])
new_order

['Name',
 'Code',
 'Full Name',
 'Region',
 'Population',
 '1800',
 '1801',
 '1802',
 '1803',
 '1804',
 '1805',
 '1806',
 '1807',
 '1808',
 '1809',
 '1810',
 '1811',
 '1812',
 '1813',
 '1814',
 '1815',
 '1816',
 '1817',
 '1818',
 '1819',
 '1820',
 '1821',
 '1822',
 '1823',
 '1824',
 '1825',
 '1826',
 '1827',
 '1828',
 '1829',
 '1830',
 '1831',
 '1832',
 '1833',
 '1834',
 '1835',
 '1836',
 '1837',
 '1838',
 '1839',
 '1840',
 '1841',
 '1842',
 '1843',
 '1844',
 '1845',
 '1846',
 '1847',
 '1848',
 '1849',
 '1850',
 '1851',
 '1852',
 '1853',
 '1854',
 '1855',
 '1856',
 '1857',
 '1858',
 '1859',
 '1860',
 '1861',
 '1862',
 '1863',
 '1864',
 '1865',
 '1866',
 '1867',
 '1868',
 '1869',
 '1870',
 '1871',
 '1872',
 '1873',
 '1874',
 '1875',
 '1876',
 '1877',
 '1878',
 '1879',
 '1880',
 '1881',
 '1882',
 '1883',
 '1884',
 '1885',
 '1886',
 '1887',
 '1888',
 '1889',
 '1890',
 '1891',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1897',
 '1898',
 '1899',
 '1900',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1908',
 '1909',
 '1910',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1916',
 '1917',
 '1918',
 '1919',
 '1920',
 '1921',
 '1922',
 '1923',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1929',
 '1930',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '1950',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022']

In [28]:
merged_df = merged_df[new_order]

In [31]:
merged_df.to_csv("data/emissions_enriched.csv", index=False)

# Visualize the data

In [42]:
emissions_2022 = merged_df[['Full Name', 'Region', '2022', 'Population']].copy()
emissions_2022["Total Emission"] = emissions_2022["2022"] * emissions_2022['Population']
emissions_2022.rename(columns={"2022": "Emissions Per Capita"})
emissions_2022

        Full Name   Region    2022  Population  Total Emission
0     Afghanistan     Asia   0.284  30560034.0    8.679050e+06
1          Angola   Africa   1.230  25177394.0    3.096819e+07
2         Albania   Europe   2.100   2860708.0    6.007487e+06
3         Andorra   Europe   5.910         NaN             NaN
4             UAE     Asia  21.100         NaN             NaN
..            ...      ...     ...         ...             ...
189         Samoa  Oceania   1.430         NaN             NaN
190         Yemen     Asia   0.395         NaN             NaN
191  South Africa   Africa   5.180         NaN             NaN
192        Zambia   Africa   0.424         NaN             NaN
193      Zimbabwe   Africa   0.804         NaN             NaN

[194 rows x 5 columns]