## Connecting to DB in python

In [6]:
from sqlite3 import connect
import pandas as pd

with connect('data/soccer.sqlite') as conn:
  query = """
    SELECT *
    FROM Player
    LIMIT 10
  """

  result = pd.read_sql(
    query,
    con=conn
  )

result
  # do stuff with that connection

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
5,6,27316,Aaron Hunt,158138,1986-09-04 00:00:00,182.88,161
6,7,564793,Aaron Kuhl,221280,1996-01-30 00:00:00,172.72,146
7,8,30895,Aaron Lennon,152747,1987-04-16 00:00:00,165.10,139
8,9,528212,Aaron Lennox,206592,1993-02-19 00:00:00,190.50,181
9,10,101042,Aaron Meijers,188621,1987-10-28 00:00:00,175.26,170

## Basic search

In [9]:
name = "Helmut%"

with connect("data/soccer.sqlite") as conn:
    query = f"""
        SELECT *
          FROM Player
         WHERE player_name LIKE '{name}'
    """
    players_df = pd.read_sql(query, con=conn)

players_df.head()

Empty DataFrame
Columns: [id, player_api_id, player_name, player_fifa_api_id, birthday, height, weight]
Index: []